import random
kelimeler = ['yazılmak', 'yatmak', 'uyumak', 'borsa', 'ülke', 'dolap', 'ünlü', 'dolaşmak', 'içmek', 'içki',
             'susmam', 'giymek', 'gitmek', 'porselen', 'ayakkabı', 'bilgisayar', 'pencere', 'düzenbaz', 'yalancı', 
             'peçete', 'selpak', 'salıncak', 'baba', 'vurgun', 'durgun', 'sinek', 'yaz', 'kış', 'cumhuriyet', 'atatürk',
             'oyuncak', 'salıncak', 'çocuk', 'naz', 'kur', 'sinek', 'böcek', 'kapı', 'şarj', 'kulaklık', 'oyun',
             'ressam', 'film', 'dizi', 'müzik', 'ayna', 'firma', 'sevgi', 'ask', 'duygusal', 'feminist', 'aldatmak', 
             'kelime', 'süzmek', 'sürgün', 'kitap', 'öğretmen', 'polis', 'öğrenmek', 'savcı', 'hakim', 'tepki', 
             'asker', 'baba', 'din', 'anne', 'ruh', 'bal', 'arı', 'güzel', 'çirkin', 'define', 'hazine', 'suçlu', 'mahkeme',
             'sanık', 'yazılım', 'korumak', 'dümen', 'gülmek', 'at', 'spor', 'dil', 'müşteki', 'müşteri', 'hak', 'hukuk',
             'mahkeme', 'yasal', 'yol', 'ölüm', 'yalan', 'gezegen', 'rütbe', 'evren', 'mars', 'dünya', 'insan', 'evlat',
             'karakter', 'kötu', 'birlik', 'birim', 'sevgi', 'etki', 'tepki', 'coşmak', 'satmak', 'bahçe', 'vergi', 'zam',
             'dar', 'geniş', 'bolluk', 'sol', 'sağ', 'müzisyen', 'sanatçı', 'karınca', 'hayvan', 'korumak', 'yük', 'yükümlülük',
             'sülük', 'makyaj', 'taraf', 'futbol', 'petek', 'doğal', 'gaz', 'elektrik', 'fatura', 'kod', 'oyun', 'telegram', 
             'yastık', 'baza', 'taraf', 'taraftar', 'dolar', 'vadi', 'havlu', 'motivasyon', 'aksiyon', 'şirket', 'sahip', 
             'tarih', 'bozgun', 'tok', 'aç', 'kahvaktı', 'lamba', 'irdelemek', 'almak', 'satmak', 'çiftçi', 'horlamak', 
             'kulaklık', 'ses', 'göz', 'kulak', 'ayak', 'bacak', 'hayat', 'doğal', 'doğa', 'hava', 'oksijen', 'temiz', 
             'pis', 'ter', 'koku', 'terlik', 'yorgan', 'kılıf', 'tabanca', 'kın', 'kılıç', 'özgüven', 'tavan', 'taban', 
             'avukat', 'avutmak', 'hakime', 'radyo', 'popüler', 'resmi', 'dilekçe', 'şikayet', 'vilayet', 'tohum', 'torun',
             'osmanlı', 'boğulmak', 'soyulmak', 'devir', 'teslim', 'kesin', 'villa', 'konut', 'proje', 'onay', 'tümen', 'tüzük',
             'üniversite', 'soba', 'boru', 'kullanmak', 'araba', 'marka', 'makyaj', 'trip', 'sirk', 'red', 'kalıp', 'kalp', 
             'cerrah', 'selamet', 'hoşlanmak', 'küsmek', 'gece', 'gündüz', 'düz', 'yokuş', 'tırmanmak', 'alınmak', 'kurulmak', 
             'sevilmek', 'pantalon', 'elbise', 'polar', 'sofra', 'aile', 'keyif', 'komutan', 'kumandan', 'burjuva', 'balıklama', 
             'sayıklamak', 'hayıflanmak', 'telefon', 'zayıflamak', 'günes', 'düzen', 'rüzgar', 'halı', 'düşman', 'sıralama', 
             'övgü', 'tel', 'ezmek', 'kesmek', 'uzay', 'bilim' 'oyuncak', 'park', 'otopark', 'bez', 'forma', 'usta', 'ütü', 'masa',
             'masal', 'yalan', 'sebep', 'sepet', 'hüner', 'hünkar', 'serçe', 'tarih', 'kader', 'yazgı', 'soy', 'fosil', 'değer', 
             'satranç', 'dama', 'petek', 'peltek', 'duvar', 'kutu', 'program', 'banka', 'faiz', 'saz', 'bal', 'arı', 'kilim', 'boncuk',
             'gelincik', 'gelinlik', 'devir', 'sedir', 'verem', 'kanser', 'grip', 'doktot', 'hemşire', 'polis', 'hastahane', 'hukuk', 'öğrenci',
             'lisans', 'memur', 'kadro', 'zırh', 'okul', 'vize', 'puan', 'sıralama', 'dayak', 'replik', 'sazlık', 'kaz', 'sıcak', 'rüzgar',
             'lodos', 'sorgu',  'kuşak', 'televizyon', 'radyo', 'gazete', 'akü', 'benzin', 'mazot', 'tarot', 'fal', 'sakız', 'sandal', 'gemi',
             'animasyon', 'sebil', 'su', 'damacana', 'sözlük', 'hata', 'kul', 'kontak', 'lens', 'ses', 'gürültü', 'çocuk', 'evlilik', 'pas', 
             'sarılmak', 'var', 'yok', 'rap', damacana', 'arı', 'böcek', 'aslan', 'köpek', 'duyar', 'duvar', 'beton', 'çelik', 'kovulmak', 
             'para', 'harçlık', 'cüzdan', 'boş', 'sürüngen', 'gece', 'gündüz', 'yalvarmak', 'koşmak', 'susmak', 'araç', 'hoşlanmak', 'görmek',
             'bakmak', 'sormak', 'duymak', 'bağırmak', 'hapishane', 'ev', 'emniyet', 'karakol', 'kamu', 'şikayet', 'ifafe', 'suç', 'cümle', 
             'özne', 'nesne', 'program', 'yazılım', 'kürk', 'günah', 'mezar', 'sebep', 'mutluluk', 'sorumluluk', 'hüzün', 'horoz', 'bornoz', 
             'borozan', 'tuhaf', 'zor', 'kolay',  'seçim', 'uçak', 'pilot', 'defter'
             ]


def kelime_sec():
    return random.choice(kelimeler)
